export interface FrameTemplate {
  id: string;
  name: string;
  label: string;
  sublabel?: string;
  description: string;
  textColor: string;
  bgColor: string;
  borderColor: string;
  borderWidth: string;
  borderRadius: string;
  padding: string;
  showArrow: boolean;
  showFrame: boolean;
  shadow: string;
}

export const frameTemplates: FrameTemplate[] = [
  {
    id: 'none',
    name: 'No Frame',
    label: '',
    description: 'Clean QR without any frame',
    textColor: '',
    bgColor: '',
    borderColor: '',
    borderWidth: '0',
    borderRadius: '0',
    padding: '0',
    showArrow: false,
    showFrame: false,
    shadow: 'none',
  },
  {
    id: 'scan-me',
    name: 'Scan Me',
    label: 'Scan Me',
    sublabel: 'with your phone camera',
    description: 'Simple call to action',
    textColor: '#ffffff',
    bgColor: '#059669',
    borderColor: '#047857',
    borderWidth: '2px',
    borderRadius: '20px',
    padding: '24px',
    showArrow: true,
    showFrame: true,
    shadow: '0 10px 30px rgba(5, 150, 105, 0.3)',
  },
  {
    id: 'scan-wifi',
    name: 'Wi-Fi',
    label: 'Scan for Wi-Fi',
    sublabel: 'connect instantly',
    description: 'Wi-Fi connection prompt',
    textColor: '#ffffff',
    bgColor: '#0f172a',
    borderColor: '#334155',
    borderWidth: '2px',
    borderRadius: '20px',
    padding: '24px',
    showArrow: true,
    showFrame: true,
    shadow: '0 10px 30px rgba(15, 23, 42, 0.3)',
  },
  {
    id: 'scan-menu',
    name: 'Menu',
    label: 'Scan for Menu',
    sublabel: 'view our dishes',
    description: 'Restaurant menu prompt',
    textColor: '#ffffff',
    bgColor: '#7c2d12',
    borderColor: '#9a3412',
    borderWidth: '2px',
    borderRadius: '20px',
    padding: '24px',
    showArrow: true,
    showFrame: true,
    shadow: '0 10px 30px rgba(124, 45, 18, 0.3)',
  },
  {
    id: 'scan-contact',
    name: 'Contact',
    label: 'Scan to Save Contact',
    sublabel: 'add to your phone',
    description: 'vCard sharing prompt',
    textColor: '#ffffff',
    bgColor: '#4f46e5',
    borderColor: '#4338ca',
    borderWidth: '2px',
    borderRadius: '20px',
    padding: '24px',
    showArrow: true,
    showFrame: true,
    shadow: '0 10px 30px rgba(79, 70, 229, 0.3)',
  },
  {
    id: 'scan-url',
    name: 'Link',
    label: 'Scan to Open',
    sublabel: 'visit the link',
    description: 'Website URL prompt',
    textColor: '#ffffff',
    bgColor: '#1e293b',
    borderColor: '#475569',
    borderWidth: '2px',
    borderRadius: '20px',
    padding: '24px',
    showArrow: true,
    showFrame: true,
    shadow: '0 10px 30px rgba(30, 41, 59, 0.3)',
  },
  {
    id: 'scan-pay',
    name: 'Pay',
    label: 'Scan to Pay',
    sublabel: 'quick & secure',
    description: 'Payment prompt',
    textColor: '#ffffff',
    bgColor: '#059669',
    borderColor: '#047857',
    borderWidth: '2px',
    borderRadius: '20px',
    padding: '24px',
    showArrow: true,
    showFrame: true,
    shadow: '0 10px 30px rgba(5, 150, 105, 0.3)',
  },
  {
    id: 'outline',
    name: 'Outline',
    label: 'Scan Me',
    sublabel: '',
    description: 'Minimal bordered frame',
    textColor: '#1e293b',
    bgColor: '#ffffff',
    borderColor: '#1e293b',
    borderWidth: '3px',
    borderRadius: '16px',
    padding: '20px',
    showArrow: false,
    showFrame: true,
    shadow: '0 4px 12px rgba(0, 0, 0, 0.08)',
  },
];
